### ISSUE TITLE
Group: Wayne, Evan, & Winter's - Email Click 

### ISSUE THREAD

**Issue by waynenovich** [jackpolifka/jackpolifka.github.io#14]
When clicking on the email, it changes the site to the email page.
- Have the email go to a new tab
- Lets users send an email and still see the site
- in it's current state, a user who would perhaps wish you to contact you about specific elements of your portfolio will have a harder time because of the redirection if they are relying on being able to see the portfolio to comment on the aforementioned specific elements.

**Comment by jackpolifka** [comment]
That's a great idea. If I want to address this issue, I need to use a contact form. Currently, something would be a wishlist idea in my opinion. I will work on it once all of the content for the site complete first.
